apiVersion: v1
kind: Service
metadata:
  name: kafkaoffsetmonitor
  labels:
    app: kafkaoffsetmonitor
spec:
  ports:

  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: kafkaoffsetmonitor

  - port: 8085
    protocol: TCP
    targetPort: 8085
    name: doorman

  selector:
    app: kafkaoffsetmonitor
