apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "kafkaoffsetmonitor"
  labels:
    service: "kafkaoffsetmonitor"
spec:
  replicas: 1
  selector:
    service: "kafkaoffsetmonitor"
  template:
    metadata:
      labels:
        service: "kafkaoffsetmonitor"
        app: "kafkaoffsetmonitor"
    spec:
      containers:

      # Pod Doorman
      - name: "doorman"
        image: "vungle/doorman:latest"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8085
          protocol: "TCP"

      # Pod
      - name: "kafkaoffsetmonitor"
        image: "vungle/kafkaoffsetmonitor:0.2.1"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
          protocol: "TCP"
        args: ["com.quantifind.kafka.offsetapp.OffsetGetterWeb", "--zk", "172.16.31.246", "--refresh", "10.seconds", "--retain", "2.days", "--port", "8080"]



